INSERT INTO contractors(ID,NAME) VALUES (1,'Abteilung Genderkompetenz');
INSERT INTO contractors(ID,NAME) VALUES (2,'Bibliothek');
INSERT INTO contractors(ID,NAME) VALUES (3,'Büro für Öffentlichkeitsarbeit');
INSERT INTO contractors(ID,NAME) VALUES (4,'Continuing Education Center');
INSERT INTO contractors(ID,NAME) VALUES (5,'Datenschutz und Dokumentenmanagement');
INSERT INTO contractors(ID,NAME) VALUES (6,'Department für Finanzen');
INSERT INTO contractors(ID,NAME) VALUES (7,'EU-Forschungssupport');
INSERT INTO contractors(ID,NAME) VALUES (8,'Forschungsmarketing');
INSERT INTO contractors(ID,NAME) VALUES (9,'Forschungs- und Transfersupport');
INSERT INTO contractors(ID,NAME) VALUES (10,'Fundraising & Sponsoring');
INSERT INTO contractors(ID,NAME) VALUES (11,'Gebäude und Technik');
INSERT INTO contractors(ID,NAME) VALUES (12,'Interne Revision');
INSERT INTO contractors(ID,NAME) VALUES (13,'International Office');
INSERT INTO contractors(ID,NAME) VALUES (14,'Personaladministration');
INSERT INTO contractors(ID,NAME) VALUES (15,'Personalentwicklung und Betriebliche Gesundheitsförderung');
INSERT INTO contractors(ID,NAME) VALUES (16,'Studienabteilung');
INSERT INTO contractors(ID,NAME) VALUES (17,'Teaching Support Center (TSC)');
INSERT INTO contractors(ID,NAME) VALUES (18,'Tieftemperaturanlagen');
INSERT INTO contractors(ID,NAME) VALUES (19,'TU.it (IT Solutions)');
INSERT INTO contractors(ID,NAME) VALUES (20,'Universitätsarchiv');
INSERT INTO contractors(ID,NAME) VALUES (21,'Universitätsentwicklung und Qualitätsmanagement');

INSERT INTO questions(id,type,latestquestion) VALUES (1,'SCALA',TRUE );
INSERT INTO questions(id,type,latestquestion) VALUES (2,'SCALA',TRUE );
INSERT INTO questions_tr(questionid, question, locale) VALUES (1,'example Question','en');
INSERT INTO questions_tr(questionid, question, locale) VALUES (1,'Beispiel Frage','de');
INSERT INTO clients(username) VALUES ('testuser1');
INSERT INTO clients(username) VALUES ('testuser2');